apiVersion: apps/v1
kind: Deployment
metadata:
  name: python
  labels:
    app: python
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: python
    spec:
      containers:
      - image: <image-name>
        name: python
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
          name: http
        - containerPort: 8001
          name: http-metrics